### Test
@path = /delay
@baseUrl = localhost:5001
@custom = hello
###

# @name {{custom}}
# @clientsCount 10
# @requestCount 100
GET https://{{baseUrl}}{{path}} HTTP/2

###
# @name basePerformance 
GET https://{{baseUrl}}{{path}}
