### Test
@path = /delay
@baseUrl = localhost:5001
@custom = hello

###
# @name {{custom}}
# @clientsCount 10
# @requestCount 100
GET https://{{baseUrl}}/ HTTP/2

###
# @name basePerformance 
# @clientsCount 10
# @requestCount 100
POST https://{{baseUrl}}/post

{"data":"hello world"}

