using System.Text;

namespace CHttpServer.Http3;

internal static class QPackStaticTable
{
    internal static readonly KnownHeaderField[] Instance =
    [
        CreateHeaderField(0, ":authority", ""),
        CreateHeaderField(1, ":path", "/"),
        CreateHeaderField(2, "Age", "0"),
        CreateHeaderField(3, "Content-Disposition", ""),
        CreateHeaderField(4, "Content-Length", "0"),
        CreateHeaderField(5, "Cookie", ""),
        CreateHeaderField(6, "Date", ""),
        CreateHeaderField(7, "Etag", ""),
        CreateHeaderField(8, "If-Modified-Since", ""),
        CreateHeaderField(9, "If-None-Match", ""),
        CreateHeaderField(10, "Last-Modified", ""),
        CreateHeaderField(11, "Link", ""),
        CreateHeaderField(12, "Location", ""),
        CreateHeaderField(13, "Referer", ""),
        CreateHeaderField(14, "Set-Cookie", ""),
        CreateHeaderField(15, ":method", "CONNECT"),
        CreateHeaderField(16, ":method", "DELETE"),
        CreateHeaderField(17, ":method", "GET"),
        CreateHeaderField(18, ":method", "HEAD"),
        CreateHeaderField(19, ":method", "OPTIONS"),
        CreateHeaderField(20, ":method", "POST"),
        CreateHeaderField(21, ":method", "PUT"),
        CreateHeaderField(22, ":scheme", "http"),
        CreateHeaderField(23, ":scheme", "https"),
        CreateHeaderField(24, ":status", "103"),
        CreateHeaderField(25, ":status", "200"),
        CreateHeaderField(26, ":status", "304"),
        CreateHeaderField(27, ":status", "404"),
        CreateHeaderField(28, ":status", "503"),
        CreateHeaderField(29, "Accept", "*/*"),
        CreateHeaderField(30, "Accept", "application/dns-message"),
        CreateHeaderField(31, "Accept-Encoding", "gzip, deflate, br"),
        CreateHeaderField(32, "Accept-Ranges", "bytes"),
        CreateHeaderField(33, "Access-Control-Allow-Headers", "cache-control"),
        CreateHeaderField(34, "Access-Control-Allow-Headers", "content-type"),
        CreateHeaderField(35, "Access-Control-Allow-Origin", "*"),
        CreateHeaderField(36, "Cache-Control", "max-age=0"),
        CreateHeaderField(37, "Cache-Control", "max-age=2592000"),
        CreateHeaderField(38, "Cache-Control", "max-age=604800"),
        CreateHeaderField(39, "Cache-Control", "no-cache"),
        CreateHeaderField(40, "Cache-Control", "no-store"),
        CreateHeaderField(41, "Cache-Control", "public, max-age=31536000"),
        CreateHeaderField(42, "Content-Encoding", "br"),
        CreateHeaderField(43, "Content-Encoding", "gzip"),
        CreateHeaderField(44, "Content-Type", "application/dns-message"),
        CreateHeaderField(45, "Content-Type", "application/javascript"),
        CreateHeaderField(46, "Content-Type", "application/json"),
        CreateHeaderField(47, "Content-Type", "application/x-www-form-urlencoded"),
        CreateHeaderField(48, "Content-Type", "image/gif"),
        CreateHeaderField(49, "Content-Type", "image/jpeg"),
        CreateHeaderField(50, "Content-Type", "image/png"),
        CreateHeaderField(51, "Content-Type", "text/css"),
        CreateHeaderField(52, "Content-Type", "text/html; charset=utf-8"),
        CreateHeaderField(53, "Content-Type", "text/plain"),
        CreateHeaderField(54, "Content-Type", "text/plain;charset=utf-8"),
        CreateHeaderField(55, "Range", "bytes=0-"),
        CreateHeaderField(56, "Strict-Transport-Security", "max-age=31536000"),
        CreateHeaderField(57, "Strict-Transport-Security", "max-age=31536000; includesubdomains"),
        CreateHeaderField(58, "Strict-Transport-Security", "max-age=31536000; includesubdomains; preload"),
        CreateHeaderField(59, "Vary", "accept-encoding"),
        CreateHeaderField(60, "Vary", "origin"),
        CreateHeaderField(61, "X-Content-Type-Options", "nosniff"),
        CreateHeaderField(62, "X-XSS-Protection", "1; mode=block"),
        CreateHeaderField(63, ":status", "100"),
        CreateHeaderField(64, ":status", "204"),
        CreateHeaderField(65, ":status", "206"),
        CreateHeaderField(66, ":status", "302"),
        CreateHeaderField(67, ":status", "400"),
        CreateHeaderField(68, ":status", "403"),
        CreateHeaderField(69, ":status", "421"),
        CreateHeaderField(70, ":status", "425"),
        CreateHeaderField(71, ":status", "500"),
        CreateHeaderField(72, "Accept-Language", ""),
        CreateHeaderField(73, "Access-Control-Allow-Credentials", "FALSE"),
        CreateHeaderField(74, "Access-Control-Allow-Credentials", "TRUE"),
        CreateHeaderField(75, "Access-Control-Allow-Headers", "*"),
        CreateHeaderField(76, "Access-Control-Allow-Methods", "get"),
        CreateHeaderField(77, "Access-Control-Allow-Methods", "get, post, options"),
        CreateHeaderField(78, "Access-Control-Allow-Methods", "options"),
        CreateHeaderField(79, "Access-Control-Expose-Headers", "content-length"),
        CreateHeaderField(80, "Access-Control-Request-Headers", "content-type"),
        CreateHeaderField(81, "Access-Control-Request-Method", "get"),
        CreateHeaderField(82, "Access-Control-Request-Method", "post"),
        CreateHeaderField(83, "Alt-Svc", ""),
        CreateHeaderField(84, "Authorization", ""),
        CreateHeaderField(85, "Content-Security-Policy", "script-src 'none'; object-src 'none'; base-uri 'none'"),
        CreateHeaderField(86, "Early-Data", "1"),
        CreateHeaderField(87, "expect-ct", ""),
        CreateHeaderField(88, "forwarded", ""),
        CreateHeaderField(89, "If-Range", ""),
        CreateHeaderField(90, "Origin", ""),
        CreateHeaderField(91, "purpose", "prefetch"),
        CreateHeaderField(92, "Server", ""),
        CreateHeaderField(93, "timing-allow-origin", ""),
        CreateHeaderField(94, "Upgrade-Insecure-Requests", "1"),
        CreateHeaderField(95, "User-Agent", ""),
        CreateHeaderField(96, "x-forwarded-for", ""),
        CreateHeaderField(97, "X-Frame-Options", "deny"),
        CreateHeaderField(98, "X-Frame-Options", "sameorigin")
    ];

    private static KnownHeaderField CreateHeaderField(int index, string name, string value) =>
        new(index, name, value);
}
