// Generated for: CHttpExtension 1.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.4.0.0
/* eslint-disable */


declare module 'node-api-dotnet' {

	export namespace CHttpExt {
		export function runAsync(
			executionName: string,
			enableRedirects: boolean,
			enableCertificateValidation: boolean,
			timeout: number,
			method: string,
			uri: string,
			version: string,
			headers: Iterable<string>,
			content: string,
			requestCount: number,
			clientsCount: number,
			callback: (arg1: string) => void,
		): Promise<string>;

		export function getDiffAsync(
			defaultColor: string,
			file1: string,
			file2: string,
		): Promise<string>;

		export function cancel(): void;
	}
}
