// Generated for: CHttpExtension 1.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.7.0.0
/* eslint-disable */

import './System.Runtime';


export namespace CHttpExt {
	export function setMsQuicPath(msquicPath: string): void;

	export function sendRequestAsync(
		enableRedirects: boolean,
		enableCertificateValidation: boolean,
		useKerberosAuth: boolean,
		timeout: number,
		method: string,
		uri: string,
		version: string,
		headers: Iterable<string>,
		body: string,
	): Promise<string>;

	export function perfMeasureAsync(
		executionName: string,
		enableRedirects: boolean,
		enableCertificateValidation: boolean,
		useKerberosAuth: boolean,
		timeout: number,
		method: string,
		uri: string,
		version: string,
		headers: Iterable<string>,
		body: string,
		requestCount: number,
		clientsCount: number,
		callback: (arg1: string) => void,
	): Promise<string>;

	export function getDiffAsync(
		file1: string,
		file2: string,
	): Promise<string>;

	export function cancel(): void;
}
