//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Net.Http {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Http3Repl.Shared.runtime.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP headers length exceeded the set limit of {0} bytes..
        /// </summary>
        internal static string net_http_headers_exceeded_length {
            get {
                return ResourceManager.GetString("net_http_headers_exceeded_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header name format is invalid..
        /// </summary>
        internal static string net_http_headers_invalid_header_name {
            get {
                return ResourceManager.GetString("net_http_headers_invalid_header_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPACK integer exceeds limits or has an overlong encoding..
        /// </summary>
        internal static string net_http_hpack_bad_integer {
            get {
                return ResourceManager.GetString("net_http_hpack_bad_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to HPACK encode the headers..
        /// </summary>
        internal static string net_http_hpack_encode_failure {
            get {
                return ResourceManager.GetString("net_http_hpack_encode_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huffman-coded literal string failed to decode..
        /// </summary>
        internal static string net_http_hpack_huffman_decode_failed {
            get {
                return ResourceManager.GetString("net_http_hpack_huffman_decode_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete header block received..
        /// </summary>
        internal static string net_http_hpack_incomplete_header_block {
            get {
                return ResourceManager.GetString("net_http_hpack_incomplete_header_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header index: {0} is outside of static table and no dynamic table entry found..
        /// </summary>
        internal static string net_http_hpack_invalid_index {
            get {
                return ResourceManager.GetString("net_http_hpack_invalid_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dynamic table size update of {0} octets is greater than the configured maximum size of {1} octets..
        /// </summary>
        internal static string net_http_hpack_large_table_size_update {
            get {
                return ResourceManager.GetString("net_http_hpack_large_table_size_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic table size update received after beginning of header block..
        /// </summary>
        internal static string net_http_hpack_late_dynamic_table_size_update {
            get {
                return ResourceManager.GetString("net_http_hpack_late_dynamic_table_size_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of headers reached with incomplete token..
        /// </summary>
        internal static string net_http_hpack_unexpected_end {
            get {
                return ResourceManager.GetString("net_http_hpack_unexpected_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an invalid header name: &apos;{0}&apos;..
        /// </summary>
        internal static string net_http_invalid_header_name {
            get {
                return ResourceManager.GetString("net_http_invalid_header_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dynamic table support.
        /// </summary>
        internal static string net_http_qpack_no_dynamic_table {
            get {
                return ResourceManager.GetString("net_http_qpack_no_dynamic_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request headers must contain only ASCII characters..
        /// </summary>
        internal static string net_http_request_invalid_char_encoding {
            get {
                return ResourceManager.GetString("net_http_request_invalid_char_encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection aborted by peer ({0})..
        /// </summary>
        internal static string net_quic_connectionaborted {
            get {
                return ResourceManager.GetString("net_quic_connectionaborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIC is not supported on this platform. See https://aka.ms/dotnetquic.
        /// </summary>
        internal static string net_quic_notsupported {
            get {
                return ResourceManager.GetString("net_quic_notsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation aborted..
        /// </summary>
        internal static string net_quic_operationaborted {
            get {
                return ResourceManager.GetString("net_quic_operationaborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream aborted by peer ({0})..
        /// </summary>
        internal static string net_quic_streamaborted {
            get {
                return ResourceManager.GetString("net_quic_streamaborted", resourceCulture);
            }
        }
    }
}
