name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CONFIGURATION: Release
  DOTNET_VERSION: 11.0.x
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install Node.js
      uses: actions/setup-node@v7
      with:
        node-version: 26.x
    - name: Install Package libmsquic
      run: |
        sudo apt update
        sudo apt install -y libmsquic
      shell: sh
    - name: Build
      run: dotnet build CHttpTools.slnx -c ${{ env.CONFIGURATION }}
    - name: Test
      run: |
        dotnet test ./tests/CHttp.Tests --no-build -c ${{ env.CONFIGURATION }}
        dotnet test ./tests/CHttpExecutor.Tests --no-build -c ${{ env.CONFIGURATION }}
        dotnet test ./tests/TestWebApplication.Tests --no-build -c ${{ env.CONFIGURATION }}
        dotnet test ./tests/CHttp.Api.Tests --no-build -c ${{ env.CONFIGURATION }}
        dotnet test ./tests/CHttpServer.Tests --no-build -c ${{ env.CONFIGURATION }}
    - name: Publish VSCE
      run: |
        pushd ./src/VSCodeExt/
        npm install
        npm run vsce-deploy-win-x64
        npm run vsce-deploy-linux-x64
        popd